### ISSUE TITLE
Option: List gets a Type Error

### ISSUE THREAD

**Issue by renekaesler** [nesk/gulp-htmlprocessor#1]
Hey guys,

when using the option _list_ for getting a list of the files that were replaced you will get the following error:

```
_stream_writable.js:247
    throw new TypeError('Unknown encoding: ' + encoding);
    ^

TypeError: Unknown encoding: encoding
    at WriteStream.setDefaultEncoding (_stream_writable.js:247:11)
    at new WriteStream (fs.js:1821:10)
    at Object.fs.createWriteStream (fs.js:1780:10)
    at HTMLProcessor.processContent (D:\projects\gsbr\node_modules\gulp-htmlproc
essor\node_modules\htmlprocessor\lib\htmlprocessor.js:177:19)
```

The problem is the use of an old version of htmlprocessor. Is it possible to upgrade the version of htmlpreprocessor?

Thanks,
Rene

**Comment by nesk** [comment]
Is there any reason to use my project rather than [Wildhoney/gulp-processhtml](https://github.com/Wildhoney/gulp-processhtml), which is the project Denis Ciccale (author of [dciccale/node-htmlprocessor](https://github.com/dciccale/node-htmlprocessor)) chose to mention in his README?

This project is old and I don't know if it really needs to be maintained nowadays.
